### ISSUE TITLE
can't connect tokenary wallet in desktop safari

### ISSUE THREAD

**Issue by grachyov** [ensdomains/ens-app-v3#608]
[tokenary](https://lil.org) connects with rainbowkit when metamask option is selected https://www.rainbowkit.com

can't connect in https://app.ens.domains though

@storywithoutend could you please help to investigate it?

**Comment by grachyov** [comment]
same on ios

**Comment by grachyov** [comment]
@sugh01 @TateB yo sorry to ping

could you please update rainbowkit?

this issue should be fixed with a newer rainbowkit version

**Comment by TateB** [comment]
we have a more up-to-date rainbowkit in #578 (viem branch), the timeline for it being on app.ens is TBD though.

**Comment by laurgk** [comment]
Note: this still doesn't work on Safari. 

Installed the extension and attempted to open the wallet app through Metamask on Safari, did nothing.

**Comment by grachyov** [comment]
@TateB could you please help fix this? it should work with a standard rainbowkit config.

**Comment by TateB** [comment]
the linked pr fixes the issue, but worth noting that the safari mobile extension seems to only work (for any site) if the website contents permission is changed from "ask" to "allow"

**Comment by laurgk** [comment]
PR has been pushed and should work soon, give it about 10 mins just incase!
